imports:
  - { resource: 'development.yml', property: 'development' }
  - { resource: 'staging.yml', property: 'staging' }
  - { resource: 'production.yml', property: 'production' }
  - { resource: 'new.yml', property: 'new' }
