export default {
  SCB: { code: '014', shortName: 'SCB', name: 'ไทยพาณิชย์' },
  BBL: { code: '002', shortName: 'BBL', name: 'กรุงเทพ' },
  KBANK: { code: '004', shortName: 'KBANK', name: 'กสิกรไทย' },
  KTB: { code: '006', shortName: 'KTB', name: 'กรุงไทย' },
  TTB: { code: '011', shortName: 'TTB', name: 'ทหารไทยธนชาต' },
  GSB: { code: '030', shortName: 'GSB', name: 'ออมสิน' },
  BAY: { code: '025', shortName: 'BAY', name: 'กรุงศรีฯ' },
  BAAC: { code: '034', shortName: 'BAAC', name: 'ธกส' },
  UOB: { code: '024', shortName: 'UOB', name: 'ยูโอบี' },
  GHB: { code: '033', shortName: 'GHB', name: 'ธอส.' },
  CIMB: { code: '022', shortName: 'CIMB', name: 'ซีไอเอ็มบี' },
  CITI: { code: '017', shortName: 'CITI', name: 'ซิตี้แบงก์' },
  DB: { code: '032', shortName: 'DB', name: 'ดอยซ์แบงก์' },
  HSBC: { code: '031', shortName: 'HSBC', name: 'เอชเอสบีซี' },
  ICBC: { code: '070', shortName: 'ICBC', name: 'ไอซีบีซี' },
  ISBT: { code: '066', shortName: 'ISBT', name: 'อิสลาม' },
  KK: { code: '069', shortName: 'KK', name: 'เกียรตินาคินภัทร' },
  LH: { code: '073', shortName: 'LH', name: 'แลนดแ์ อนดเ์ ฮา้ ส' },
  MHCB: { code: '039', shortName: 'MHCB', name: 'มิซูโฮ' },
  SCBT: { code: '020', shortName: 'SCBT', name: 'สแตนดารด์ชาร์เตอร์' },
  SMBC: { code: '018', shortName: 'SMBC', name: 'ซูมิโตโม มิตซุย' },
  TCRB: { code: '071', shortName: 'TCRB', name: 'ไทยเครดิต' },
  TISCO: { code: '067', shortName: 'TISCO', name: 'ทิสโก้' },
  TMB: { code: '011', shortName: 'TMB', name: 'ทหารไทย' },
};
