export default {
  bbl: {
    id: 0,
    officialName: 'BANGKOK BANK PUBLIC COMPANY LTD.',
    niceName: 'Bangkok Bank',
    thaiName: 'ธนาคารกรุงเทพ',
  },
  kbank: {
    id: 1,
    officialName: 'KASIKORNBANK PUBLIC COMPANY LTD.',
    niceName: 'Kasikornbank',
    thaiName: 'ธนาคารกสิกรไทย',
  },
  rbs: {
    id: 2,
    officialName: 'THE ROYAL BANK OF SCOTLAND PLC',
    niceName: 'Royal Bank of Scotland',
    thaiName: 'รอยัล แบงก์ ออฟ สกอตแลนด์',
  },
  ktb: {
    id: 3,
    officialName: 'KRUNG THAI BANK PUBLIC COMPANY LTD.',
    niceName: 'Krungthai Bank',
    thaiName: 'ธนาคารกรุงไทย',
  },
  jpm: {
    id: 4,
    officialName: 'JPMORGAN CHASE BANK, NATIONAL ASSOCIATION',
    niceName: 'J.P. Morgan',
    thaiName: 'เจพีมอร์แกนเชส',
  },
  mufg: {
    id: 5,
    officialName: 'THE BANK OF TOKYO-MITSUBISHI UFJ, LTD.',
    niceName: 'Bank of Tokyo-Mitsubishi UFJ',
    thaiName: 'ธนาคารโตเกียว-มิตซูบิชิ ยูเอฟเจ',
  },
  ttb: {
    id: 6,
    officialName: 'TMBTHANACHART BANK PUBLIC COMPANY LTD.',
    niceName: 'TMBThanachart Bank',
    thaiName: 'ธนาคารทหารไทยธนชาต',
  },
  scb: {
    id: 7,
    officialName: 'SIAM COMMERCIAL BANK PUBLIC COMPANY LTD.',
    niceName: 'Siam Commercial Bank',
    thaiName: 'ธนาคารไทยพาณิชย์',
  },
  citi: {
    id: 8,
    officialName: 'CITIBANK, N.A.',
    niceName: 'Citibank',
    thaiName: 'ซิตี้แบงก์',
  },
  smbc: {
    id: 9,
    officialName: 'SUMITOMO MITSUI BANKING CORPORATION',
    niceName: 'Sumitomo Mitsui Banking Corporation',
    thaiName: 'ซูมิโตโม มิตซุย แบงกิ้ง คอร์ปอเรชั่น',
  },
  sc: {
    id: 10,
    officialName: 'STANDARD CHARTERED BANK (THAI) PUBLIC COMPANY LIMITED',
    niceName: 'Standard Chartered (Thai)',
    thaiName: 'ธนาคารสแตนดาร์ดชาร์เตอร์ด',
  },
  cimb: {
    id: 11,
    officialName: 'CIMB THAI BANK PUPBLIC COMPANY LTD.',
    niceName: 'CIMB Thai Bank',
    thaiName: 'ธนาคาร ซีไอเอ็มบี ไทย',
  },
  uob: {
    id: 12,
    officialName: 'UNITED OVERSEAS BANK (THAI) PUBLIC COMPANY LIMITED',
    niceName: 'United Overseas Bank (Thai)',
    thaiName: 'ธนาคารยูโอบี',
  },
  bay: {
    id: 13,
    officialName: 'BANK OF AYUDHYA PUBLIC COMPANY LTD.',
    niceName: 'Bank of Ayudhya (Krungsri)',
    thaiName: 'ธนาคารกรุงศรีอยุธยา',
  },
  mega: {
    id: 14,
    officialName: 'MEGA INTERNATIONAL COMMERCIAL BANK PUBLIC COMPANY LIMITED',
    niceName: 'Mega International Commercial Bank',
    thaiName: 'ธนาคาร เมกะ สากลพาณิชย์ จํากัด',
  },
  boa: {
    id: 15,
    officialName: 'BANK OF AMERICA, NATIONAL ASSOCIATION',
    niceName: 'Bank of America',
    thaiName: 'แบงค์ออฟอเมริกา',
  },
  cacib: {
    id: 16,
    officialName: 'CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK',
    niceName: 'Crédit Agricole',
    thaiName: 'ธนาคารเครดิตอากริโคล',
  },
  gsb: {
    id: 17,
    officialName: 'THE GOVERNMENT SAVINGS BANK',
    niceName: 'Government Savings Bank',
    thaiName: 'ธนาคารออมสิน',
  },
  hsbc: {
    id: 18,
    officialName: 'THE HONGKONG AND SHANGHAI BANKING CORPORATION LTD.',
    niceName: 'Hongkong and Shanghai Banking Corporation',
    thaiName: 'ธนาคารเอชเอสบีซี ประเทศไทย',
  },
  db: {
    id: 19,
    officialName: 'DEUTSCHE BANK AG.',
    niceName: 'Deutsche Bank',
    thaiName: 'ธนาคารดอยซ์แบงก์',
  },
  ghb: {
    id: 20,
    officialName: 'THE GOVERNMENT HOUSING BANK',
    niceName: 'Government Housing Bank',
    thaiName: 'ธนาคารอาคารสงเคราะห์',
  },
  baac: {
    id: 21,
    officialName: 'BANK FOR AGRICULTURE AND AGRICULTURAL COOPERATIVES',
    niceName: 'Bank for Agriculture and Agricultural Cooperatives',
    thaiName: 'ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร',
  },
  mb: {
    id: 22,
    officialName: 'MIZUHO BANK, LTD.',
    niceName: 'Mizuho Bank',
    thaiName: 'ธนาคารมิซูโฮ จํากัด',
  },
  bnp: {
    id: 23,
    officialName: 'BNP PARIBAS',
    niceName: 'BNP Paribas',
    thaiName: 'ธนาคารบีเอ็นพี พารีบาส์',
  },
  ibank: {
    id: 25,
    officialName: 'ISLAMIC BANK OF THAILAND',
    niceName: 'Islamic Bank of Thailand',
    thaiName: 'ธนาคารอิสลามแห่งประเทศไทย',
  },
  tisco: {
    id: 26,
    officialName: 'TISCO BANK PUBLIC COMPANY LIMITED',
    niceName: 'Tisco Bank',
    thaiName: 'ธนาคารทิสโก้',
  },
  kk: {
    id: 27,
    officialName: 'KIATNAKIN BANK PUBLIC COMPANY LIMITED',
    niceName: 'Kiatnakin Bank',
    thaiName: 'ธนาคารเกียรตินาคิน',
  },
  icbc: {
    id: 28,
    officialName: 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA (THAI) PUBLIC COMPANY LIMITED',
    niceName: 'Industrial and Commercial Bank of China (Thai)',
    thaiName: 'ธนาคารไอซีบีซี (ไทย)',
  },
  tcrb: {
    id: 29,
    officialName: 'THE THAI CREDIT RETAIL BANK PUBLIC COMPANY LIMITED',
    niceName: 'Thai Credit Retail Bank',
    thaiName: 'ธนาคารไทยเครดิต',
  },
  lhb: {
    id: 30,
    officialName: 'LAND AND HOUSES BANK PUBLIC COMPANY LIMITED',
    niceName: 'Land and Houses Bank',
    thaiName: 'ธนาคารแลนด์ แอนด์ เฮ้าส์',
  },
};
